[[command]]
cmd = '''^(g|p)?make(\s|$)'''
rules = [
	['''^C(XX|C) ''', "37"],
	['''^(LD|AR) ''', "33"],	
	['''^(p|g)?make(\[\d+\])?: \*\*\*''', "1;31"],
	['''^(p|g)?make(\[\d+\])?: ''', "36"],
	[''':\d+: recipe for target '.*' failed''', "1;31"],
	['''\.c(c|pp|xx)?:\d+:\d+: (fatal )?error:''', "1;41"],
	['''\.c(c|pp|xx)?:\d+: warning:''', "43;30"],
	['''^\s+\^$''', "1;37"],
	[''':.* UP-TO-DATE$''', "32"],
	[''':.* SKIPPED$''', "33"],
]

[[command]]
cmd = '''^svn diff'''
rules = [
	['''^=+$''', "1;34"],
	['''^-''', "1;31"],
	['''^\+''', "1;32"],
	['''^@@''', "1;34"],
	['''^svn: E''', "1;41"],
]